server:
  port: 8080

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://60.204.157.19:3306/blog
      username: root
      password: J2EE_Lerjiu
  redis:
    host: 60.204.157.19
    port: 6379
    password: J2EE_Lerjiu
    lettuce:
      pool:
        max-active: 32
        max-idle: 16
        min-idle: 8
  mail:
    host: smtp.qq.com
    username: 1426239779@qq.com
    password: xxriiplbrnkphhjg
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          auth: true
        ssl:
          enable: true
    protocol: smtps
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 1000MB
  elasticsearch:
    uris: http://60.204.157.19:9200

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.blog.domain

redis-expire-time:
  verifycode: 300
  token: 259200

file:
  path: /static/**
  location: /home/blog/
  avatar: avatar/
  article-img: article_img/

es:
  index:
    article: articles

search:
  page-size: 20
  max-page: 50