server:
  port: 8080

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/blog
      username: root
      password: 122381
  redis:
    host: localhost
    port: 6379
    username: lerjiu
    password: 122381
    lettuce:
      pool:
        max-active: 32
        max-idle: 16
        min-idle: 8
  mail:
    host: smtp.qq.com
    username: 1426239779@qq.com
    password: xxriiplbrnkphhjg
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          auth: true
        ssl:
          enable: true
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.blog.domain

redis-expire: 300
